openapi: 3.0.0
info:
  title: Investment Questionnaire Reconciliation
  description: The service is used to reconcile investment questionnaire based to specified input parameters.
  version: v1
paths:
  /questionnaire/{accountId}:
    get:
      description: The method is used to reconcile values of investment questionnaire according to specified input parameters.
      parameters:
        - name: X-Corellation-ID
          in: header
          required: true
          schema:
            $ref: "#/components/headers/X-Correlation-ID"
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: timestamp
          in: querz
          required: true
          schema:
            type: string
        - name: location
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
              nullable: true
              enum:
                - CZ
                - SK
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/instantSyncResponse'
        '204':
          description: No Content
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal server error
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
components:
  schemas:
    instantSyncResponse:
      type: object
      properties:
        clientQuestionnaireId:
          type: string
          title: Id
          description: Client Questionnaire identifier
          minLength: 1
          maxLength: 50
        businessChangeDate:
          type: string
          format: date-time
          title: Validity date
          description: The date and time of the beginning of the client questionnaire validity
        businessStatus:
          type: string
          title: Business status
          description: Business status of the list
    Error: 
      required: 
        - "code"
        - "message"
      type: object
      properties: 
        code: 
          type: integer
          format: int32
          description: "RFC 7231 error code"
          example: "1234"
        message: 
          type: string
          description: "The content of the attribute is a combination of a generally defined error and a description of a generally defined error according to the type and sensitivity of the service."
          example: "Daily limit is exceeded."
        timestamp: 
          type: string
          description: "Date and time of the error according to RFC5424"
          example: "2022-01-12T23:20:50.52"
        index:
          type: string
          description: "Contains information about the X-Correlation-ID or Elastic Search index"
          example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
        internal:
          type: object
          properties:
            code:
              type: string
              description: "Internal error code according to the application / system which is the service provider."
              example: "1092092"
            message:
              type: string
              description: "Internal description of the error according to the application / system which is the service provider."
              example: "PTS daily limit is exceeded."
  headers: 
    X-Correlation-ID: 
      description: "Unique request's/operation's identifier."
      required: true
      style: "simple"
      explode: false
      schema: 
        maxLength: 36
        type: "string"
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"