openapi: 3.0.1
info:
  title: ACMARK CRM DIGI API
  description: API rozhraní pro integraci CRM s DIGI.
  contact:
    name: Martin Veselý
    email: mvesely@acmark.com
  version: '1.0'
paths:
  /api/v1/Account/check:
    post:
      tags:
        - Account
      summary: Account reconciliation
      parameters:
        - name: X-Corellation-ID
          in: header
          description: ''
          required: true
          schema:
            type: string
        - name: from
          in: query
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          schema:
            type: string
            format: date-time
        - name: mode
          in: query
          description: <p>Variants:</p><ul></ul>
          required: true
          schema:
            enum:
              - sync
              - async
            type: string
            description: <p>Members:</p><ul></ul>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckKlientRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CheckKlientRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CheckKlientRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckKlientResponse'
        '204':
          description: No Content
        '400':
          description: <br>***400*** - Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Prázdný nebo chybný token. Detail případně v hlavičce www-authenticate.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '404':
          description: "<br>***ERR404-0*** - Account not found.\r\n<br>***404*** - Not Found."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: <br>***500*** - Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
  /api/v1/Contact/check:
    post:
      tags:
        - Contact
      summary: Contact reconciliation
      parameters:
        - name: X-Corellation-ID
          in: header
          required: true
          schema:
            type: string
        - name: from
          in: query
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          schema:
            type: string
            format: date-time
        - name: mode
          in: query
          description: <p>Variants:</p><ul></ul>
          required: true
          schema:
            enum:
              - sync
              - async
            type: string
            description: <p>Members:</p><ul></ul>
      requestBody:
        description: Rodné číslo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckKontaktRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/CheckKontaktRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CheckKontaktRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckKontaktResponse'
        '204':
          description: No Content
        '400':
          description: <br>***400*** - Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Prázdný nebo chybný token. Detail případně v hlavičce www-authenticate.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '404':
          description: "<br>***ERR404-0*** - Contact not found.\r\n<br>***404*** - Not Found."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: <br>***500*** - Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
components:
  schemas:
    CheckKlientRequest:
      type: object
      properties:
        accountGUID:
          type: string
          format: uuid
        accountKLID:
          type: string
          nullable: true
        rc:
          type: string
          nullable: true
        ico:
          type: string
          nullable: true
        nid:
          type: string
          nullable: true
        vid:
          type: string
          nullable: true
        zam:
          type: string
          nullable: true
      additionalProperties: false
    CheckKlientResponse:
      type: object
      properties:
        firstName:
          type: string
          description: Jméno
          nullable: true
        nameSurname:
          type: string
          description: Název/příjmení
          nullable: true
        identifierType:
          $ref: '#/components/schemas/CrmOptionSet'
        identifier:
          type: string
          description: Hodnota identifikátoru
          nullable: true
        klientId:
          type: string
          description: Klient ID (KLID)
          nullable: true
        location:
          $ref: '#/components/schemas/CrmOptionSet'
        banker:
          type: string
          description: Bankéř (API Code)
          nullable: true
        clientStatus:
          $ref: '#/components/schemas/CrmOptionSet'
      additionalProperties: false
    CheckKontaktRequest:
      type: object
      properties:
        contactGUID:
          type: string
          format: uuid
        contactKLID:
          type: string
          nullable: true
        rc:
          type: string
          nullable: true
      additionalProperties: false
    CheckKontaktResponse:
      type: object
      properties:
        firstName:
          type: string
          description: Jméno
          nullable: true
        nameSurname:
          type: string
          description: Název/příjmení
          nullable: true
        rc:
          type: string
          description: RČ kontaktu, jiný identifikátor kontakt nemá
          nullable: true
        klientId:
          type: string
          description: Klient ID (KLID)
          nullable: true
        location:
          $ref: '#/components/schemas/CrmOptionSet'
        banker:
          type: string
          description: Bankéř (API Code)
          nullable: true
      additionalProperties: false
    ClientErrorResponseType:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
          readOnly: true
      additionalProperties: false
    CrmOptionSet:
      type: object
      properties:
        value:
          type: integer
          format: int32
        label:
          type: string
          nullable: true
      additionalProperties: false
    ServerErrorResponseType:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
          readOnly: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: '**_CRM JWT Auth Token_** (Server To Server Authentication, JWT Token is encrypted).</br>Enter CRM JWT Bearer token **_only_**'
      scheme: bearer
      bearerFormat: JWT
security:
  - Bearer: []
