openapi: 3.0.0
info:
  title: Bank news Reconciliation
  description: The service is used to reconcile Bank news sets based to specified input parameters.
  version: v1
paths:
  /api/v1/BankNews/settings:
    get:
      description: The method returns list of available Bank news
      parameters:
        - $ref: "#/components/parameters/X-Correlation-ID"
        - name: from
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: 2022-01-15
        - name: to
          in: query
          required: false
          schema:
            type: string
            format: date-time
            example: 2022-02-17
        - name: mode
          in: query
          required: true
          schema:
            type: string
            enum:
              - sync
              - async
      responses:
        '200':
          description: OK
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                type: object
                # Struktura objektu bude doplněna po začlenění do existujícího CRM API.
        '204':
          description: No Content
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
        '400':
          description: Bad Request
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: Unauthorized
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Forbidden
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"

  /api/v1/BankNews/settings/{crmIdType}/{crmId}:
    get:
      description: The method returns Bank news settings for one Client
      parameters:
        - $ref: "#/components/parameters/X-Correlation-ID"
        - name: crmIdType
          in: path
          required: true
          schema:
            type: string  
            enum:
              - EMPTY
              - AccountGUID
              - AccountKLID
              - ContactGUID
              - ContactKLID
              - MessagesFromBankGUID            
        - name: crmId
          in: path
          required: true
          schema:
            type: string              
        - name: mode
          in: query
          required: true
          schema:
            type: string
            enum:
              - sync
              - async
      responses:
        '200':
          description: OK
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                type: object
                # Struktura objektu bude doplněna po začlenění do existujícího CRM API.
        '204':
          description: No Content
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
        '400':
          description: Bad Request
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: Unauthorized
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: Forbidden
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error: 
      required: 
        - "code"
        - "message"
      type: object
      properties: 
        code: 
          type: integer
          format: int32
          description: "RFC 7231 error code"
          example: "1234"
        message: 
          type: string
          description: "The content of the attribute is a combination of a generally defined error and a description of a generally defined error according to the type and sensitivity of the service."
          example: "Daily limit is exceeded."
        timestamp: 
          type: string
          description: "Date and time of the error according to RFC5424"
          example: "2022-01-12T23:20:50.52"
        index:
          type: string
          description: "Contains information about the X-Correlation-ID or Elastic Search index"
          example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
        internal:
          type: object
          properties:
            code:
              type: string
              description: "Internal error code according to the application / system which is the service provider."
              example: "1092092"
            message:
              type: string
              description: "Internal description of the error according to the application / system which is the service provider."
              example: "PTS daily limit is exceeded."
    X-Correlation-ID:
      description: "Correlation identifier for request and response pairing."
      type: string
      format: uuid
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"

  headers:
    X-Correlation-ID: 
      description: "Correlation identifier for request and response pairing."
      required: true
      schema: 
        $ref: "#/components/schemas/X-Correlation-ID"

  parameters:
    X-Correlation-ID:
      name: X-Correlation-ID
      in: header
      required: true
      description: "Correlation identifier for request and response pairing."
      schema:
        $ref: "#/components/schemas/X-Correlation-ID"
