# 2022-11-25 - 1.0.0 - Pavel HrdliÄka - Initial version of API.
openapi: 3.0.0
info:
  title: IBANInfo
  description: The service is used to get information about account according to IBAN parameter.
  version: 1.0.0
paths:
  /ibanInfo/{iban}:
    get:
      description: Get information about account according to IBAN parameter.
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          description: Correlation identifier for request and response pairing.
          schema:
            $ref: "#/components/schemas/X-Correlation-ID"
        - name: traceparent
          in: header
          required: true
          description: "Tracing parameter according to W3C Trace Context standard."
          schema:
            $ref: "#/components/schemas/traceparent"
        - name: iban
          in: path
          required: true
          schema:
            type: string
            maxLength: 34
            example: "CZ4907100000000000123457"
      responses:
        '200':
          description: OK
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IbanInfoResponse'
        '400':
          description: Bad Request
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"   
        '409':
          description: Conflict
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"   
        '500':
          description: Internal Server Error
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
components:
  schemas:
    IbanInfoResponse: 
      required: 
        - "accountPrefix"
        - "accountNumber"
        - "bic"
        - "SEPAProductRegistration"
      type: object
      properties: 
        accountPrefix: 
          type: string
          minLength: 1
          maxLength: 6
          description: "Account number prefix according to BBAN format."
          example: "000000"
        accountNumber: 
          type: string
          minLength: 1
          maxLength: 10
          description: "Account number according to BBAN format"
          example: "1234567890"
        bankCode: 
          type: string
          minLength: 1
          maxLength: 4
          description: "Account number bank code according to BBAN format."
          example: "0800"
        bic: 
          type: string
          minLength: 7
          maxLength: 11
          format: int32
          description: "Bank identification code"
          example: "KOMBCZPP"
        SEPAProductRegistration:
          type: object
          required:
           - "isSCT"
           - "isSDDCOR"
           - "isSDDB2B"
           - "isSCTINST"
          properties:
            isSCT:
              description: Is registered for SCT?
              type: boolean
            isSDDCOR:
              description: Is registered for SDD COR?
              type: boolean
            isSDDB2B:
              description: Is registered for SDDB2B?
              type: boolean
            isSCTINST:
              description: Is registered for SCTINST?
              type: boolean
    Error:
      required:
        - code
        - timestamp
        - index
        - version
        - errors
      type: object
      properties:
        code:
          description: RFC 7231 error code
          type: string
          example: 400
        timestamp:
          description: Date and time of the error according to RFC5424
          type: string
          format: date-time
          example: 2022-01-12T23:20:50.52
        index:
          description: Contains information about the X-Correlation-ID or Elastic Search index.
          type: string
          example: 4adde395-ebef-4552-bd39-cbdaf63305a9
        version:
          description: Version of the error response structure
          type: string
          enum:
           - '2.0'
          example: 2.0
        errors:
          description: Array of errors
          type: array
          items:
            type: object
            required:
              - jtCode
              - message
            properties:
              jtCode:
                description: Business error code if defined in CSC or RFC 7231 error code
                type: string
                example: 9903
              message:
                description: Error description defined in CSC according to the type and sensitivity of the service.
                type: string
                example: Daily limit is exceeded.
              sourceSystem:
                description: Name of the system, where error was detected.
                type: string
                example: PTS
              severity:
                description: Exception severity
                type: string
                enum:
                  - error
                  - warning
                example: error
              params:
                description: Array of message parameters
                type: array
                items:
                  type: object
                  required:
                    - paramName
                    - paramValue
                  properties:
                    paramName:
                      description: The name of the parameter in the message string, e.g. 'Missing or invalid element %1' -> paramName = 1
                      type: string
                      example: 1
                    paramValue:
                      description: The value of the parameter in the message string
                      type: string
                      example: amount
        internalErrors:
          description: Array of internal error codes and error descriptions according to the service provider
          type: array
          items:
            type: object
            properties:
              code:
                description: Internal error code according to the application / system which is the service provider.
                type: string
              message:
                description: Internal description of the error according to the application / system which is the service provider.
                type: string
                example: Daily limit is exceeded.
    X-Correlation-ID:
      description: "Correlation identifier for request and response pairing."
      type: string
      format: uuid
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      maxLength: 55
      type: string
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
  headers: 
    X-Correlation-ID: 
      description: "Correlation identifier for request and response pairing."
      required: true
      schema: 
        $ref: "#/components/schemas/X-Correlation-ID"
    