# 2022-12-07 – 0.0.1 - Vít Joachymstál - Initial version
openapi: 3.0.0
info:
  title: Fees Calculation
  description: Service for fees calculation
  version: 0.0.1
paths:
  /feesCalculation:
    post:
      description: >-
        Metoda vrací vypočtené hodnoty poplatků a daně


        Výpočet je založen na volání TOPAS funkce TOP_ITF_PKG.FeeCalculation. 


        Omezení TOPAS služby:

         - Nelze zasílat každý poplatek zvlášť.
         - Poplatky a daně jsou uvedeny ve stejné měně jako vstupní částka pokynu.

         V eBroker dochází k dohledání/doplnění potřebných TOPAS/TA souřadnic na základě vstupních paramterů: 

         - ID produktu v TOPASu (z Mapy produktů a trhů) - vybírá se nejprioritnější vhodný produkt na základě vstupů: trh, směr, kategorie klienta, preferovaný účet depozitáře
         - Trh v TOPASu.
         - Způsob přijetí v TOPASu (komunikační kanál).
         - Zda je cenný papír cílově evidován v TOPASu nebo TA včetně výjimek z pravidla evidovaných v eBroker (Prav_Vloz_Pok_Ext).
         - V případě že volající vyplní ID portfolia v eBr souřadnicích, dohledá topasId (KID). Pokud jsou vyplněny obě hodnoty, bude použito topasId 
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          description: "Correlation identifier for request and response pairing."
          schema:
            $ref: "#/components/schemas/X-Correlation-ID"        
        - name: X-Request-ID
          in: header
          required: true
          description: "Unique HTTP request's identifier."
          schema:
            $ref: "#/components/schemas/X-Request-ID"
        - name: traceparent
          in: header
          required: true
          description: "Tracing parameter according to W3C Trace Context standard."
          schema:
            $ref: "#/components/schemas/traceparent"
      requestBody:
        description: feesCalculationRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/feesCalculationRequest'
      responses:
        "200":
          description: OK
          headers:  
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/feesCalculationResponse"
        "400":
          description: >-
            Bad Request


             | Message                    | Code                                      | 
             |----------------------------|-------------------------------------------|       
             | PORTFOLIOIDS_IS_MISSING     | portfolioIds is missing - required         |
             | INSTRUMENTIDS_IS_MISSING   | instrumentIds is missing - required       |
             | CURRENCY_IS_MISSING        | currency is missing - required            |
             | AMOUNT_IS_MISSING          | amount is missing - required              |
             | MARKETID_IS_MISSING        | marketId is missing - required            |
             | SIDEID_IS_MISSING          | sideId is missing - required              |
             | TRADEDATE_IS_INVALID         | tradeDate is in wrong format - YYYY-MM-DD | 

          headers:
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"            
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: >-
            Not Found

             | Message                        | Code                             |
             |--------------------------------|----------------------------------|
             | PORTFOLIOID_NOT_FOUND          | portfolioId not found            |
             | INSTRUMENTID_NOT_FOUND         | instrumentId not found           |
             | CURRENCY_NOT_FOUND             | currency not found               |
             | MARKETID_NOT_FOUND             | marketId not found               |
             | SIDEID_NOT_FOUND               | sideId not found                 |
             | COMMUNICATIONCHANNEL_NOT_FOUND | communicationChannelId not found |
             
          headers:
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"            
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: >-
            Internal server error

             | Message          | Code                                     | 
             |------------------|------------------------------------------|
             | UNEXPECTED_ERROR | Unexpected error - \<Technical Details\> |
             | DB_ERROR         | DB exception - <exception text>          |

          headers:
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"            
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "503":
          description: >-
            Service Unavailable

             | Message        | Code                           | 
             |----------------|--------------------------------|
             | DB_UNAVAILABLE | Unable to connect to DB server |
             
          headers:
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"            
            X-Request-ID:
              $ref: "#/components/headers/X-Request-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    feesCalculationRequest:
      required: 
        - "portfolioIds"
        - "instrumentIds"
        - "currency"
        - "amount"        
        - "marketId"
        - "sideId"
      type: object
      properties:
        portfolioIds:
          description: "Identifikátory portfolia"
          type: object
          properties:
            topasId:
              type: integer
              description: "Identifikace Portfolia v TOPAS (KID)"
            ebrokerId:
              type: integer
              description: "Identifikace portfolia v eBroker"
        instrumentIds:
          description: "Identifikátory cenných papírů"
          type: object
          properties:
            ebrokerId:
              type: integer
              description: "Identifikace CP v eBroker"
            ccpId:
              type: integer
              description: "Identifikace CP v CCP"
        currency:
          type: string
          description: "ISO 4217 kód měny obchodu,poplatků a daní"
        tradeDate:
          type: string
          format: date
          description: "Datum výpočtu poplatků s ohledem na výjimky, pokud není uveden tak sysdate"
        amount:
          type: number
          description: "částka pokynu včetně AÚV, oddělovač '.'"
        marketId:
          type: string
          description: "Aplikační kód trhu. Zdroj hodnot - číselník InvExchanges"
        sideId:
          type: string
          description: "Aplikační kód směru pokynu. Zdroj hodnot - číselník InvOrderDirection"
        nett:
          type: boolean
          description: "True: poplatky se připočítavají k částce pokynu (amount), False: poplatky jsou součástí částky pokynu (použitelné pro objemové pokyny - volume order). V základu - True."
        communicationChannelId:
          type: string
          description: "Aplikační kód komunikačního kanálu použitého k podání pokynu. Výchozí hodnota = jinak. Zdroj hodnot - číselník CommunicationChannel"
    feesCalculationResponse:
      required: 
        - "feeCurrency"
      type: object
      properties:
        brokerFee:
          type: number
          description: "Poplatek brokerovi, resp. poplatek vypočtený z TA"
        tradeFee:
          type: number
          description: "Poplatek makléři"
        serviceFee:
          type: number
          description: "Poplatek za služby"
        tax:
          type: number
          description: "Daň"
        feeCurrency:
          type: string
          description: "ISO kód 4217 měny všech poplatků a daně"
    Error: 
      required: 
        - "code"
        - "message"
      type: object
      properties: 
        code: 
          type: integer
          format: int32
          description: "RFC 7231 error code"
          example: "404"
        message: 
          type: string
          description: "The content of the attribute is a combination of a generally defined error and a description of a generally defined error according to the type and sensitivity of the service."
          example: "Not Found"
        timestamp: 
          type: string
          description: "Date and time of the error according to RFC5424"
          example: "2022-01-12T23:20:50.52"
        index:
          type: string
          description: "Contains information about the X-Correlation-ID or Elastic Search index"
          example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
        internal:
          type: object
          properties:
            code:
              type: string
              description: "Internal error code according to the application / system which is the service provider."
              example: "portfolioId not found"
            message:
              type: string
              description: "Internal description of the error according to the application / system which is the service provider."
              example: "PORTFOLIOID_NOT_FOUND"
    X-Correlation-ID:
      description: "Correlation identifier for request and response pairing."
      type: string
      format: uuid
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
    X-Request-ID:
      description: "Unique HTTP request's identifier."
      type: string
      format: uuid
      example: "8sddff95-essf-4125-bd39-cvgaf63305a9"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      maxLength: 55
      type: string
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
  headers:
    X-Correlation-ID: 
      description: "Correlation identifier for request and response pairing."
      required: true
      schema: 
        $ref: "#/components/schemas/X-Correlation-ID"
    X-Request-ID:
      description: "Unique HTTP request's identifier."
      required: true
      schema: 
        $ref: "#/components/schemas/X-Request-ID"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      required: true
      schema: 
        $ref: "#/components/schemas/traceparent"