swagger: '2.0'
info:
  description: hotDocs REST API for assembling documents
  version: v0
  title: hotDocsSIT
host: 'czpav00447.jtfg.com:888'
schemes:
  - http
security:
  - default: []
paths:
  /api/HotDocs/VariablesInfo:
    get:
      tags:
        - HotDocs
      operationId: HotDocs_VariablesInfo
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - name: templatePath
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /api/HotDocs/DialogsInfo:
    get:
      tags:
        - HotDocs
      operationId: HotDocs_DialogsInfo
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - name: templatePath
          in: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /api/HotDocs/AssembleDocument:
    post:
      tags:
        - HotDocs
      operationId: HotDocs_AssembleDocument
      consumes:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - application/x-www-form-urlencoded
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - in: body
          name: modelAssembleDocument
          required: true
          schema:
            $ref: '#/definitions/AssembleDocumentModel'
      responses:
        '200':
          description: OK
          schema:
            type: object
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /api/HotDocs/AssembleDocumentWithAnx:
    post:
      tags:
        - HotDocs
      operationId: HotDocs_AssembleDocumentWithAnx
      consumes:
        - application/json
        - text/json
        - application/xml
        - text/xml
        - application/x-www-form-urlencoded
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters:
        - in: body
          name: modelAssembleDocument
          required: true
          schema:
            $ref: '#/definitions/AssembleDocumentModelAnx'
      responses:
        '200':
          description: OK
          schema:
            type: object
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /api/HotDocs/AvailableTemplates:
    get:
      tags:
        - HotDocs
      operationId: HotDocs_AvailableTemplates
      consumes: []
      produces:
        - application/json
        - text/json
        - application/xml
        - text/xml
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            type: object
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
securityDefinitions:
  default:
    type: oauth2
    authorizationUrl: 'https://test.com'
    flow: implicit
definitions:
  'KeyValuePair[String,Object]':
    type: object
    properties:
      key:
        type: string
      value:
        type: object
        properties: {}
  AssembleDocumentModelAnx:
    type: object
    properties:
      TemplatePath:
        type: string
      Answers:
        type: string
      OutputFormat:
        type: string
  AssembleDocumentModel:
    type: object
    properties:
      TemplatePath:
        type: string
      TemplateData:
        type: array
        items:
          $ref: '#/definitions/KeyValuePair[String,Object]'
      OutputFormat:
        type: string
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - 'http://czpav02223.jtfgtest.com:888'
  type: http
x-wso2-basePath: /hotDocs/v1
x-wso2-transports:
  - https
x-wso2-application-security:
  security-types:
    - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
