# 2022-12-16 – 0.0.1 - Vít Joachymstál - Initial version
openapi: 3.0.0
info:
  title: CreatePortfolio
  description: Portfolio creation service
  version: 0.0.1
paths:
  /portfolio/{location}:
    post:
      tags:
        - CratePortfolio
      description: Založení portfolia
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/X-Correlation-ID"
        - name: traceparent
          in: header
          required: true
          description: "Tracing parameter according to W3C Trace Context standard."
          schema:
            $ref: "#/components/schemas/traceparent"
        - name: location
          in: path
          required: true
          description: "Lokace portfolia v alfa2 kodu"          
          schema:
            $ref: "#/components/schemas/location"  
      requestBody:
        description: CreatePortfolioRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createPortfolioRequest'
        required: true
      responses:
        "200":
          description: OK
          headers:  
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createPortfolioResponse"
        "400":
          description: >-
            Bad Request

             | Message         | Code                 |
             |-----------------|----------------------|
             | CRMID_NOT_FOUND | CRMID does not exist |

          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: >-
            Not Found

             | Code | Message  | 
             |------|----------|
             |404   |Not Found |

          headers:
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    location:
     type: string
     enum:
       - 'CZ'
       - 'SK'
    createPortfolioRequest:
      required:
        - owner
        - portfolioCustomName
        - marginTradingAllowed
      type: object
      properties:
        owner:
          required:
            - crmId
          type: object
          description: Vlastník portfolia
          properties:
            crmId:
              description: Unikátní identifikátor v CRM
              type: string
              maxLength: 10
              minLength: 10
        portfolioCustomName:
          type: string
          description: Název portfolia
        marginTradingAllowed:
          type: boolean
          description: Příznak povolení maržových obchodů
        creditLimit:
          type: number
          description: Maximální úvěrový limit
    createPortfolioResponse:
      required:
        - portfolioIds
      type: object
      properties:
        portfolioIds:
           description: Identifikátory portfolia
           type: object
           required:
           - ebrokerId
           properties:
             ebrokerId:
               type: integer
               description: Identifikátor portfolia v eBroker
    Error:
      required:
        - code
        - timestamp
        - index
        - version
        - errors
      type: object
      properties:
        code:
          description: RFC 7231 error code
          type: string
          example: 400
        timestamp:
          description: Date and time of the error according to RFC5424
          type: string
          format: date-time
          example: 2022-01-12T23:20:50.52
        index:
          description: Contains information about the X-Correlation-ID or Elastic Search index.
          type: string
          example: 4adde395-ebef-4552-bd39-cbdaf63305a9
        version:
          description: Version of the error response structure
          type: string
          enum:
           - '2.0'
          example: 2.0
        errors:
          description: Array of errors
          type: array
          items:
            type: object
            required:
              - jtCode
              - message
            properties:
              jtCode:
                description: Business error code if defined in CSC or RFC 7231 error code
                type: string
                example: 9903
              message:
                description: Error description defined in CSC according to the type and sensitivity of the service.
                type: string
                example: Daily limit is exceeded.
              sourceSystem:
                description: Name of the system, where error was detected.
                type: string
                example: ADP
              severity:
                description: Exception severity
                type: string
                enum:
                  - error
                  - warning
                example: error
              params:
                description: Array of message parameters
                type: array
                items:
                  type: object
                  required:
                    - paramName
                    - paramValue
                  properties:
                    paramName:
                      description: The name of the parameter in the message string, e.g. 'Missing or invalid element %1' -> paramName = 1
                      type: string
                      example: 1
                    paramValue:
                      description: The value of the parameter in the message string
                      type: string
                      example: amount
        internalErrors:
          description: Array of internal error codes and error descriptions according to the service provider
          type: array
          items:
            type: object
            properties:
              code:
                description: Internal error code according to the application / system which is the service provider.
                type: string
              message:
                description: Internal description of the error according to the application / system which is the service provider.
                type: string
                example: Daily limit is exceeded.
    X-Correlation-ID:
      description: "Correlation identifier for request and response pairing."
      type: string
      format: uuid
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      maxLength: 55
      type: string
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
  headers:
    X-Correlation-ID: 
      description: "Correlation identifier for request and response pairing."
      required: true
      schema: 
        $ref: "#/components/schemas/X-Correlation-ID"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      required: true
      schema: 
        $ref: "#/components/schemas/traceparent"