openapi: 3.0.1
info:
  title: Sezam API
  description: Defines API for client credentials management services and Authentication and autorization services.
  version: 3.3.3-SNAPSHOT
servers:
  - url: https://sezam-jtcz-test.jtsritp4.assecosk.local/sezamapi
    description: Generated server url
tags:
  - name: UCM API
    description: Defines API for user credential management. **Contains back end to back end integration services.**
paths:
  /ucm/v1/users/{userId}:
    get:
      tags:
        - UCM API
      summary: GET USER operation
      description: |-
        Return user detail information.

        Validation:
        - user existence
        - mandatory and format of input parameters
        - csfr token - required if operation is called from operator/admin console
        - channel validity

        Result codes: 

        - 10001 - Internal server error
        - 10002 - Bad request
        - 10102 - Bad cross-site request forgery token
        - 10201 - Parameter is required
        - 10202 - Mininum length for parameter
        - 10203 - Maximum length for parameter
        - 10204 - Parameter has wrong format
        - 10205 - Mininum value for parameter
        - 10206 - Maximum value for parameter
        - 10207 - Parameter is not base64 string!
        - 12001 - Entity was not found for given parameter
        - 12606 - No Session
        - 13001 - Channel is not active
        - 13002 - Channel not found
        - 13206 - Decryption error

        Roles: hasAnyRole('ROLE_API_UCM', 'ROLE_API_UCM_USER_GET')
      operationId: getUserDetailV1
      parameters:
        - name: userId
          in: path
          description: User identifier
          required: true
          style: simple
          schema:
            type: string
        - name: channel
          in: query
          description: The code of caller channel for auditing purpose
          required: true
          style: form
          schema:
            type: integer
        - name: channelOperatorId
          in: query
          description: Name of operator for given channel
          required: false
          style: form
          schema:
            type: string
        - name: X-XSRF-TOKEN
          in: header
          description: Csrf token
          required: false
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successfull response for get user detail operation.
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/GetUserDetailOkResultV1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
      security:
        - basicAuth: []
    delete:
      tags:
        - UCM API
      summary: USER CANCEL operation
      description: |-
        Cancel user.

        Validation:
        - user existence, user must not be already canceled
        - mandatory and format of input parameters
        - csfr token - required if operation is called from operator/admin console
        - channel validity

        Result codes: 

        - 10001 - Internal server error
        - 10002 - Bad request
        - 10101 - Resource was already updated - optimistic lock
        - 10102 - Bad cross-site request forgery token
        - 10201 - Parameter is required
        - 10202 - Mininum length for parameter
        - 10203 - Maximum length for parameter
        - 10204 - Parameter has wrong format
        - 10205 - Mininum value for parameter
        - 10206 - Maximum value for parameter
        - 10207 - Parameter is not base64 string!
        - 12001 - Entity was not found for given parameter
        - 12111 - User doesn't exist or is not valid
        - 12606 - No Session
        - 13001 - Channel is not active
        - 13002 - Channel not found
        - 13206 - Decryption error

        Roles: hasAnyRole('ROLE_API_UCM', 'ROLE_API_UCM_USER_DELETE')
      operationId: deleteUserV1
      parameters:
        - name: userId
          in: path
          description: User identifier
          required: true
          style: simple
          schema:
            type: string
        - name: reasonNote
          in: query
          description: Reason note for description of state change by operator
          required: false
          style: form
          schema:
            type: string
        - name: version
          in: query
          description: Version is field in database used for optimistic locking
          required: true
          style: form
          schema:
            type: integer
        - name: channel
          in: query
          description: The code of caller channel for auditing purpose
          required: true
          style: form
          schema:
            type: integer
        - name: channelOperatorId
          in: query
          description: Name of operator for given channel
          required: false
          style: form
          schema:
            type: string
        - name: X-XSRF-TOKEN
          in: header
          description: Csrf token
          required: false
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: Successfull response for user cancel operation.
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCredentialManagementResult'
      security:
        - basicAuth: []
components:
  schemas:
    UserAliasV1:
      required:
        - alias
        - userId
        - validFrom
        - version
      type: object
      properties:
        alias:
          type: string
          description: Alias of the user
        userId:
          type: string
          description: User ID
        validFrom:
          type: string
          description: Valid from user`s alias. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
        validTo:
          type: string
          description: Valid to user`s alias. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
          nullable: true
        version:
          type: integer
          description: Version for optimistic locking
          format: int64
      description: Alias of user
    UserDetailChannelV1:
      required:
        - channelId
      type: object
      properties:
        channelId:
          type: integer
          description: Code of channel
          format: int32
        channelRoles:
          type: array
          description: Codes of channel roles
          nullable: true
          items:
            type: integer
            description: Codes of channel roles
            format: int32
            nullable: true
        lastSuccesfulLoginIP:
          type: string
          description: Last Login Succesful IP
          nullable: true
        lastSuccesfulLoginTimeStamp:
          type: string
          description: Last Login Succesful TimeStamp. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
          nullable: true
        lastUnsuccesfulLoginIP:
          type: string
          description: Last Login Unsuccesful IP
          nullable: true
        lastUnsuccesfulLoginTimeStamp:
          type: string
          description: Last Login Unsuccesful TimeStamp. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
          nullable: true
      description: Response for user channel detail
      nullable: true
    UserDetailResponseV1:
      required:
        - user
        - userState
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserDetailV1'
        userState:
          $ref: '#/components/schemas/UserDetailStateV1'
        channels:
          type: array
          description: User channels
          nullable: true
          items:
            $ref: '#/components/schemas/UserDetailChannelV1'
      description: Response for user detail
    UserDetailStateV1:
      required:
        - created
        - id
        - operator
        - state
        - userId
        - validFrom
        - version
      type: object
      properties:
        id:
          type: integer
          description: ID of the state
          format: int64
        userId:
          type: string
          description: User ID
        state:
          type: string
          description: State of user
          enum:
            - ACTIVE
            - CANCELED
            - DENIED
            - BLOCKED
        validFrom:
          type: string
          description: Valid from. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
        blockReason:
          type: string
          description: Block reason
          nullable: true
          enum:
            - TOO_MANY_LOGIN_ATTEMPTS
            - TOO_MANY_REGISTER_MTOKEN_ATTEMPTS
            - TOO_MANY_AUTHORIZATION_PAYMENT_ATTEMPTS
            - TOO_MANY_CHANGE_CLIENT_PIN_ATTEMPTS
            - TOO_MANY_ATTEMPTS
            - BASED_ON_FRAUD_PREVENTION_SYSTEM
            - UNDEFINED
        blockedTo:
          type: string
          description: Blocked to. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
          nullable: true
        deniedReason:
          type: string
          description: Denied reason
          nullable: true
          enum:
            - INITIATED_BY_CLIENT
            - INITIATED_BY_BRANCH
            - INITIATED_BY_HEADQUARTER
        reasonNote:
          type: string
          description: Reason of change state
          nullable: true
        operator:
          type: string
          description: Operator who made state change
        channelId:
          type: integer
          description: Code of channel
          format: int32
          nullable: true
        created:
          type: string
          description: Created. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
        description:
          type: string
          description: Description of state
          nullable: true
        version:
          type: integer
          description: Row version
          format: int64
      description: Response for user state
    UserDetailV1:
      required:
        - login
        - state
        - userId
        - validFrom
        - version
      type: object
      properties:
        userId:
          type: string
          description: User ID
        login:
          type: string
          description: Login of the user
        aliases:
          type: array
          description: List of user's aliases
          items:
            $ref: '#/components/schemas/UserAliasV1'
        externalId:
          type: string
          description: External ID of user
          nullable: true
        description:
          type: string
          description: Description of user
          nullable: true
        state:
          type: string
          description: State
          enum:
            - ACTIVE
            - CANCELED
            - DENIED
            - BLOCKED
        validFrom:
          type: string
          description: Valid from. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
        validTo:
          type: string
          description: Valid to. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
          nullable: true
        blockedTo:
          type: string
          description: Blocked to. Format is yyyy-MM-dd'T'HH:mm:ss.SSSZ
          nullable: true
        version:
          type: integer
          description: Version for optimistic locking
          format: int64
      description: Response for user detail
    UserCredentialManagementResult:
      required:
        - errorText
        - resultCode
      type: object
      properties:
        resultCode:
          type: string
          description: 'Result code: 0 - OK, otherwise error code'
        errorText:
          type: string
          description: Error description
      description: Result of UCM operation
    GetUserDetailOkResultV1:
      required:
        - errorText
        - resultCode
      type: object
      properties:
        resultCode:
          type: string
          description: 'Result code: 0 - OK, otherwise error code'
        errorText:
          type: string
          description: Error description
        response:
          $ref: '#/components/schemas/UserDetailResponseV1'
      description: Response for get user operation
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
