# 2023-01-20 - 0.1.0 - Aleš Kratochvíl - Initial version
# 2023-02-10 - 0.1.1 - Aleš Kratochvíl - marketId > marketFormId; Czech description; English description polishing
# 2023-02-28 - 0.1.2 - Aleš Kratochvíl - requestId > applicationId
openapi: 3.0.0
info:
  title: CRM RealTimeDataAccess Reconciliation
  description: The service is used to reconcile values of CRM RealTimeDataAccess according to specified input parameters.
  version: 0.1.2
paths:
  /realTimeDataAccess:
    get:
      tags:
        - RealTimeDataAccess
      description: The method is used to reconcile several Questionnaires with theirs Real-time data access settings according to specified input parameters.
      parameters:
        - $ref: "#/components/parameters/X-Correlation-ID"
        - $ref: "#/components/parameters/traceparent"
        - in: query
          name: filter
          required: false
          style: form
          explode: true
          schema:
            type: object
            properties:
              accountId:
                type: string
                format: uuid
                description: AccountGUID (číslo účtu)
              klientId:
                type: string
                minLength: 10
                maxLength: 10
                description: AccountKLID (číslo klienta)
              filledWhenFrom:
                type: string
                format: date
                description: omezení výběru od - datum změny entity
                example: 2023-01-13
              filledWhenTo:
                type: string
                format: date
                description: omezení výběru do - datum změny entity
                example: 2023-02-14
              marketFormId:
                type: string
                description: id burzy, pro kterou byl vyplněn dotazník
                example: NASDAQ
                # Values according to codebook RTDataForms > Key 1 (Unique value identifier).
                # Values according to codebook InvExchanges > Function 4 (poskytování Real-time dat).
            oneOf:
              - required: [accountId]
              - required: [klientId]
              - required: [marketFormId]
      responses:
        '204':
          description: No Content
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
        '400':
          description: Bad Request
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /realTimeDataAccess/{applicationId}:
    get:
      tags:
        - RealTimeDataAccess
      description: The method is used to reconcile the concrete Questionnaire with its Real-time data access settings.
      parameters:
        - $ref: "#/components/parameters/X-Correlation-ID"
        - $ref: "#/components/parameters/traceparent"
        - name: applicationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: instance formuláře v CRM
      responses:
        '204':
          description: No Content
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
        '400':
          description: Bad Request
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /health:
    get:
      tags:
        - Default
      description: Health check endpoint
      parameters:
        - $ref: "#/components/parameters/X-Correlation-ID"
        - $ref: "#/components/parameters/traceparent"
      responses:
        '200':
          description: OK
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Endpoint status
                    example: "UP"
        '400':
          description: Bad Request
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers:
            X-Correlation-ID:
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent:
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      required:
        - "code"
        - "message"
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: "RFC 7231 error code."
          example: "503"
        message:
          type: string
          description: "The content of the attribute is a combination of a generally defined error and a description of a generally defined error according to the type and sensitivity of the service."
          example: "Daily limit is exceeded."
        timestamp:
          type: string
          description: "Date and time of the error according to RFC5424"
          example: "2022-08-24T05:14:15+02:00"
        index:
          type: string
          description: "Contains information about the X-Correlation-ID or Elastic Search index"
          example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
        internal:
          type: object
          properties:
            code:
              type: string
              description: "Internal error code according to the application / system which is the service provider."
              example: "1092092"
            message:
              type: string
              description: "Internal description of the error according to the application / system which is the service provider."
              example: "Daily limit is exceeded."
    X-Correlation-ID:
      description: "Correlation identifier used to match request with response in async REST communication through the interface and to deduplicate messages in sync/async REST communication where data changes occur."
      type: string
      format: uuid
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
    traceparent:
      description: "Tracing parameter according to W3C Trace Context standard."
      type: string
      maxLength: 55
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
  headers:
    X-Correlation-ID:
      required: true
      schema:
        $ref: "#/components/schemas/X-Correlation-ID"
    traceparent:
      required: true
      schema:
        $ref: "#/components/schemas/traceparent"
  parameters:
    X-Correlation-ID:
      name: X-Correlation-ID
      in: header
      required: true
      schema:
        $ref: "#/components/schemas/X-Correlation-ID"
    traceparent:
      name: traceparent
      in: header
      required: true
      schema:
        $ref: "#/components/schemas/traceparent"