openapi: 3.0.0
info:
  title: collectionAccountDisponibleBalance
  description: The service is used to calculate disponible balance for collection account.
  version: 1.0.0
paths:
  /disponibleBalance/{referenceSystem}/{portfolioId}:
    get:
      description: Method returns disponible balance
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          description: Correlation identifier for request and response pairing.
          schema:
            $ref: "#/components/schemas/X-Correlation-ID"
        - name: traceparent
          in: header
          required: true
          description: "Tracing parameter according to W3C Trace Context standard."
          schema:
            $ref: "#/components/schemas/traceparent"
        - name: referenceSystem
          in: path
          required: true
          description: "System according to portfolioId"
          schema:
            type: string
            maxLength: 3
            example: "top"
            enum:
              - top
              - ebr
        - name: portfolioId
          in: path
          required: true
          description: "Portfolio ID"
          schema:
            type: string
        - name: reportCurrency
          in: query
          required: true
          description: "Currency to which will be all values for PreSetled balances on all accounts calculated. Also currency in which will be BuyPower returned. (CZK / EUR / USD)"
          schema:
            type: string
            example: CZK
            enum:
              - CZK
              - EUR
              - USD
      responses:
        '200':
          description: OK
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisponibleBalanceResponse'      
        '400':
          description: Bad Request
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
components:
  schemas:
    DisponibleBalanceResponse: 
      required: 
        - "portfolioId"
        - "portfolioId2"
        - "portfolioTotalPresettled"
        - "reportCurrency"
        - "portfolioBuyPowerTotal"
        - "accountBalances"
      type: object
      properties: 
        portfolioId: 
          type: integer
          description: "ID of portfolio in Topas."
        portfolioId2: 
          type: integer
          description: "ID of portfolio in eBroker."
        portfolioTotalPresettled: 
          type: number
          description: "Total value of Presetled balance in given portfolio in reportCurrency."
        reportCurrency: 
          type: string
          description: "Reference currency, in which are balances on collectionAccount calculated."
          example: "KOMBCZPP"
        portfolioBuyPowerTotal:
          type: array
          items:
            $ref: '#/components/schemas/PortfolioBuyPowerTotalItem'
        accountBalances:
          type: array
          items:
            $ref: '#/components/schemas/AccountBalanceItem'
    PortfolioBuyPowerTotalItem:
      type: object
      required:
       - "accountCurrency"
       - "buyPower"
      properties:
        accountCurrency:
          description: "Currency in which is calculate BuyPower. Its calculation of all currencies defined in MRM."
          type: string
        buyPower:
          description: "Currency in which is calculate BuyPower. Its calculation of all currencies defined in MRM."
          type: number
    AccountBalanceItem:
      type: object
      required:
       - "accountNumber"
       - "bankCode"
       - "accountCurrency"
       - "accountBalanceAPresettled"
       - "accountBalanceRPresettled"
       - "accountBalanceADisponible"
      properties:
        accountNumber:
          description: "Number of collection account."
          type: string
        bankCode:
          description: "Bank code of collection account (5800 or 8300)"
          type: string
        accountCurrency:
          description: "Currency of collection account."
          type: string
        accountBalanceAPresettled:
          description: "Presettled balance of collection account in currency of collection account."
          type: number
        accountBalanceRPresettled:
          description: "Presetled balance of collection account in reference currency (reportCurrency)"
          type: number
        accountBalanceADisponible:
          description: "Disponible balances of collection account - amount, which can be transferred."
          type: number
    Error: 
      required: 
        - "code"
        - "message"
      type: object
      properties: 
        code: 
          type: integer
          format: int32
          description: "RFC 7231 error code"
          example: "1234"
        message: 
          type: string
          description: "The content of the attribute is a combination of a generally defined error and a description of a generally defined error according to the type and sensitivity of the service."
          example: "Daily limit is exceeded."
        timestamp: 
          type: string
          description: "Date and time of the error according to RFC5424"
          example: "2022-01-12T23:20:50.52"
        index:
          type: string
          description: "Contains information about the X-Correlation-ID or Elastic Search index"
          example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
        internal:
          type: object
          properties:
            code:
              type: string
              description: "Internal error code according to the application / system which is the service provider."
              example: "1092092"
            message:
              type: string
              description: "Internal description of the error according to the application / system which is the service provider."
              example: "Daily limit is exceeded."
    X-Correlation-ID:
      description: "Correlation identifier for request and response pairing."
      type: string
      format: uuid
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      maxLength: 55
      type: string
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
  headers: 
    X-Correlation-ID: 
      description: "Correlation identifier for request and response pairing."
      required: true
      schema: 
        $ref: "#/components/schemas/X-Correlation-ID"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      schema: 
        $ref: "#/components/schemas/traceparent"
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
            