openapi: 3.0.0
info:
  title: cardDetailReconciliation
  description: The service is used to reconcile values of card detail according to specified input parameters.
  version: 1.0.0
paths:
  /cardDetail:
    get:
      description: "The method is used to reconcile values of card detail. Priority of query parameters: Only one query parameter at time is applied.  If there is more than one query parameter in request, other parameters will be not used. Priority is given by order in swagger. (first query parameter = highest priority)"
      parameters:
        - name: X-Correlation-ID
          in: header
          required: true
          description: Correlation identifier for request and response pairing.
          schema:
            $ref: "#/components/schemas/X-Correlation-ID"
        - name: traceparent
          in: header
          required: true
          description: "Tracing parameter according to W3C Trace Context standard."
          schema:
            $ref: "#/components/schemas/traceparent"
        - name: cardId
          in: query
          required: false
          description: "Card Id"
          schema:
            type: string
        - name: aPan
          in: query
          required: false
          description: "Card number on card which status have changed. CardNumber and MbrNum together are unique key"
          schema:
            type: string
        - name: ownerCrmId
          in: query
          required: false
          description: "CRM ID of card owner."
          schema:
            type: string
            example: "1000017222"
        - name: masterAccountId
          in: query
          required: false
          description: "QST master account number"
          schema:
            type: string
            example: "20170105092351404111"
        - name: openDateFrom
          in: query
          required: false
          description: "Open date of the credit account."
          schema:
            type: string
            example: "2022-01-17"
        - name: cardExpiration
          in: query
          required: false
          description: "Expiration date in YYMM format."
          schema:
            type: string
            example: "2201"

        

      responses:
        '204':
          description: No Content
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
        '400':
          description: Bad Request
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '404':
          description: Not Found
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
        '503':
          description: Service Unavailable
          headers: 
            X-Correlation-ID: 
              $ref: "#/components/headers/X-Correlation-ID"
            traceparent: 
              $ref: "#/components/headers/traceparent"
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error: 
      required: 
        - "code"
        - "message"
      type: object
      properties: 
        code: 
          type: integer
          format: int32
          description: "RFC 7231 error code"
          example: "1234"
        message: 
          type: string
          description: "The content of the attribute is a combination of a generally defined error and a description of a generally defined error according to the type and sensitivity of the service."
          example: "Daily limit is exceeded."
        timestamp: 
          type: string
          description: "Date and time of the error according to RFC5424"
          example: "2022-01-12T23:20:50.52"
        index:
          type: string
          description: "Contains information about the X-Correlation-ID or Elastic Search index"
          example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
        internal:
          type: object
          properties:
            code:
              type: string
              description: "Internal error code according to the application / system which is the service provider."
              example: "1092092"
            message:
              type: string
              description: "Internal description of the error according to the application / system which is the service provider."
              example: "Daily limit is exceeded."
    X-Correlation-ID:
      description: "Correlation identifier for request and response pairing."
      type: string
      format: uuid
      example: "4adde395-ebef-4552-bd39-cbdaf63305a9"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      maxLength: 55
      type: string
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
  headers: 
    X-Correlation-ID: 
      description: "Correlation identifier for request and response pairing."
      required: true
      schema: 
        $ref: "#/components/schemas/X-Correlation-ID"
    traceparent: 
      description: "Tracing parameter according to W3C Trace Context standard."
      schema: 
        $ref: "#/components/schemas/traceparent"
      example: "00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01"
            