# 2023-04-18 – 1.0.1 - Pavel Hrdlička - added enum option "Combined" to parameter "productType"
openapi: 3.0.0
info:
  title: Vracia zoznam technických ID produktov
  version: v1
servers:
  - url: https://apitest.jtfg.com/RelevantProductSIT/v2
security:
  - default: []
paths:
  /productId:
    get:
      operationId: DIGI_BankingProductIdsByFilter
      parameters:
        - name: productType
          in: query
          description: Typ produktu
          required: true
          style: form
          explode: true
          schema:
            title: 'Possible values: Card, CurrentAccount, NoticeDeposit, TermDeposit, Combined'
            type: string
            description: Typ produktu
            enum:
              - Card
              - CurrentAccount
              - NoticeDeposit
              - TermDeposit
              - Combined
          example: productType
        - name: clientPhase
          in: query
          description: Fáze klienta
          required: true
          style: form
          explode: true
          schema:
            title: 'Posiible values: new, existing'
            type: string
            description: Fáze klienta
            nullable: true
          example: clientPhase
        - name: contractType
          in: query
          description: Typ smlouvy
          required: true
          style: form
          explode: true
          schema:
            type: string
            description: Typ smlouvy
            nullable: true
          example: contractType
        - name: publishingArea
          in: query
          description: Publikační místo
          required: true
          style: form
          explode: true
          schema:
            type: string
            description: Publikační místo
            nullable: true
          example: publishingArea
        - name: date
          in: query
          description: Datum
          required: true
          style: form
          explode: true
          schema:
            type: string
            description: Datum
            format: date-time
            nullable: true
          example: '2011-02-19T20:45:12.123+02:00'
        - name: prtype
          in: query
          description: PRTYPE
          required: false
          style: form
          explode: true
          schema:
            type: string
            description: PRTYPE
            nullable: true
          example: prtype
        - name: currency
          in: query
          description: Měna
          required: false
          style: form
          explode: true
          schema:
            type: string
            description: Měna
            nullable: true
          example: currency
      responses:
        '200':
          description: Standard response
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    title: PK technical product ID
                    type: array
                    items:
                      type: string
                      nullable: true
                nullable: true
              example:
                productId:
                  - productId
            application/xml:
              schema:
                type: object
                properties:
                  productId:
                    title: PK technical product ID
                    type: array
                    items:
                      type: string
                      nullable: true
                nullable: true
        '204':
          description: Standard response
        '400':
          description: Client error response
          content:
            text/plain:
              schema:
                type: string
        '403':
          description: Operation forbidden reponse
        '404':
          description: Operation not found response
        '406':
          description: Operation output data not available in content type acceptable by client
        '500':
          description: Server error response
          content:
            text/plain:
              schema:
                type: string
        '503':
          description: Server not available response
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://apitest.jtfg.com/authorize
          scopes: {}
