# 2023-03-27 - 1.0.1 - Aleš Kratochvíl - quaestorAccountId addition
openapi: 3.0.1
info:
  title: AutoSweep Service API
  description: API rozhraní pro práci s AutoSweep.
  contact:
    name: Martin Veselý
    email: mvesely@acmark.cz
  version: '1.0.1'
servers:
  - url: https://api-devint.jtfgtest.com/AutoSweep/v1
security:
  - default: []
paths:
  /api/v1/Autosweep/status/{clientId}/{location}:
    get:
      tags:
        - Autosweep
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: location
          in: path
          description: <p>Variants:</p><ul></ul>
          required: true
          style: simple
          explode: false
          schema:
            type: string
            description: <p>Members:</p><ul></ul>
            enum:
              - EMPTY
              - CZ
              - SK
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAutosweepStatusResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /api/v1/Autosweep/validate/{clientId}/{location}:
    get:
      tags:
        - Autosweep
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: location
          in: path
          description: <p>Variants:</p><ul></ul>
          required: true
          style: simple
          explode: false
          schema:
            type: string
            description: <p>Members:</p><ul></ul>
            enum:
              - EMPTY
              - CZ
              - SK
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAutosweepValidationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                type: string
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /api/v1/Autosweep/activate/{clientId}/{location}:
    patch:
      tags:
        - Autosweep
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: location
          in: path
          description: <p>Variants:</p><ul></ul>
          required: true
          style: simple
          explode: false
          schema:
            type: string
            description: <p>Members:</p><ul></ul>
            enum:
              - EMPTY
              - CZ
              - SK
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /api/v1/Autosweep/deactivate/{clientId}/{location}:
    patch:
      tags:
        - Autosweep
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: location
          in: path
          description: <p>Variants:</p><ul></ul>
          required: true
          style: simple
          explode: false
          schema:
            type: string
            description: <p>Members:</p><ul></ul>
            enum:
              - EMPTY
              - CZ
              - SK
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /api/v1/Autosweep/set/{clientId}/{location}:
    put:
      tags:
        - Autosweep
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: location
          in: path
          description: <p>Variants:</p><ul></ul>
          required: true
          style: simple
          explode: false
          schema:
            type: string
            description: <p>Members:</p><ul></ul>
            enum:
              - EMPTY
              - CZ
              - SK
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AutosweepAccount'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AutosweepAccount'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AutosweepAccount'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
  /api/v1/Autosweep/delete/{clientId}/{location}/{currencyCode}:
    delete:
      tags:
        - Autosweep
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: location
          in: path
          description: <p>Variants:</p><ul></ul>
          required: true
          style: simple
          explode: false
          schema:
            type: string
            description: <p>Members:</p><ul></ul>
            enum:
              - EMPTY
              - CZ
              - SK
        - name: currencyCode
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientErrorResponseType'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
            text/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponseType'
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  schemas:
    AutosweepAccount:
      type: object
      properties:
        currency:
          type: string
          description: ISO3 kód měny (musí být vyplněno)
          nullable: true
        bban:
          type: string
          description: číslo účtu v BBAN formátu (musí být vyplněný právě jeden z trojice quaestorAccountId/IBAN/BBAN - jinak priorita klesá zleva doprava)
          nullable: true
        iban:
          type: string
          description: číslo účtu ve formátu IBAN (musí být vyplněný právě jeden z trojice quaestorAccountId/IBAN/BBAN - jinak priorita klesá zleva doprava)
          nullable: true
        quaestorAccountId:
          type: string
          description: identifikátor účtu systému Quaestor (musí být vyplněný právě jeden z trojice quaestorAccountId/IBAN/BBAN - jinak priorita klesá zleva doprava)
          nullable: true
      additionalProperties: false
    ClientErrorResponseType:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
          readOnly: true
      additionalProperties: false
    GetAutosweepStatusResponse:
      type: object
      properties:
        enabled:
          type: boolean
          description: Příznak jestli má klient aktivní AutoSweep
        accounts:
          type: array
          description: Kolekce aktivních účtů
          nullable: true
          items:
            $ref: '#/components/schemas/AutosweepAccount'
      additionalProperties: false
    GetAutosweepValidationResponse:
      type: object
      properties:
        validationResult:
          type: boolean
          description: Výsledek, zda pro klienta lze aktivovat AutoSweep
        message:
          type: string
          description: Informace o výsledku jednotlivých dílčích validací
          nullable: true
      additionalProperties: false
    ServerErrorResponseType:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
          readOnly: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: Enter JWT Bearer token **_only_**
      scheme: bearer
      bearerFormat: JWT
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api-devint.jtfgtest.com/authorize
          scopes: {}
